# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8c500d1008848259da09e6e7452d50f12bf2cfcf9f6dc3fbd33a5f38bd2fc7648ee1d10e876417395b2753c33bd0ff972a8c78a6384dbde415e5b3dfc020461

test:
  secret_key_base: 0b70b35ec0a1ccb4faac75ff1d2140342c0db44d5286f36baec86eaf4e410527083b5c7afd298f27a425a95d06fc49fa885125f0f90799467f6a9e2f4bf55f6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
